---
#-------------------------------
# General Site Settings
name: Cup of Gamedev
title: Cup of Gamedev
logo: "images/logo.png"
description: "Take your gamedev info a cup at a time!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cupofgamedev.com" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: remtaine
  site: https://www.remtaine.com
  bio: "Hi, I'm Remtaine, an indie gamedev. I write about my experiences and thoughts in game development!"
  image: "images/efigi400x400.png"
  avatar: "images/efigi400x400.png"

# Example of adding a new link to the section author - {name: "Github", link: "https://github.com"}
author-social:
  - { name: "Twitter", link: "https://twitter.com/remtaine" }
  - { name: "Github", link: "https://github.com/remtaine" }
  #- { name: "Facebook", link: "https://facebook.com" }
  #- { name: "Pinterest", link: "https://pinterest.com" }

#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
contact:
  - { icon: "ion-logo-twitter", link: "https://twitter.com" }
  #- { icon: "ion-logo-facebook", link: "https://facebook.com" }
  #- { icon: "ion-logo-dribbble", link: "https://dribbble.com" }
  #- { icon: "ion-logo-instagram", link: "https://instagram.com" }
  #- { icon: "ion-logo-pinterest", link: "https://pinterest.com" }
  - { icon: "ion ion-logo-github", link: "https://github.com" }

#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Gallery section (Footer)
gallery:
  name: Gallery
  images:
    - alt: "Minimalism"
      url: "/images/17.jpg"
    - alt: "Minimalism"
      url: "/images/07.jpg"
    - alt: "Minimalism"
      url: "/images/08.jpg"
    - alt: "Minimalism"
      url: "/images/22.jpg"
    - alt: "Minimalism"
      url: "/images/10.jpg"
    - alt: "Minimalism"
      url: "/images/21.jpg"
    - alt: "Minimalism"
      url: "/images/29.jpg"
    - alt: "Minimalism"
      url: "/images/30.jpg"
    - alt: "Minimalism"
      url: "/images/31.jpg"

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: https://cupofgamedev.us2.list-manage.com/subscribe/post?u=a502e4ca3eb62f2279c5567a0&amp;id=8489c9a232 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed
